#!/usr/bin/env python3
"""
Incremental CPG Parser Service for Lab 04 (Task 2)
Author: Sang (Data Engineer - Python Core)
"""

import argparse
import hashlib
import json
import os
import sys
import time
from typing import List, Dict, Any
from cpg_parser import parse_python_file

# Schema validation (optional if jsonschema installed)
try:
    import jsonschema
    JSONSCHEMA_AVAILABLE = True
except ImportError:
    JSONSCHEMA_AVAILABLE = False


TOPIC_NODES = "node_events"
TOPIC_EDGES = "edge_events"
TOPIC_METADATA = "source_metadata_events"
TOPIC_ERRORS = "parser_error_events"


def load_schemas(schema_dir: str) -> Dict[str, Dict[str, Any]]:
    """Load JSON schemas for validation."""
    schemas = {}
    if not os.path.exists(schema_dir):
        return schemas

    mappings = {
        TOPIC_NODES: "node_event.schema.json",
        TOPIC_EDGES: "edge_event.schema.json",
        TOPIC_METADATA: "source_metadata_event.schema.json",
        TOPIC_ERRORS: "parser_error_event.schema.json",
    }

    for topic, filename in mappings.items():
        filepath = os.path.join(schema_dir, filename)
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                schemas[topic] = json.load(f)
    return schemas


def validate_message(message: Dict[str, Any], schema: Dict[str, Any]) -> bool:
    """Validate JSON message against schema if jsonschema is available."""
    if not JSONSCHEMA_AVAILABLE or not schema:
        return True
    try:
        jsonschema.validate(instance=message, schema=schema)
        return True
    except jsonschema.ValidationError as ve:
        print(f"[WARN] Schema validation failed: {ve.message}", file=sys.stderr)
        return False


def discover_python_files(target_dir: str, exclude_tests: bool = True) -> List[str]:
    """Find all Python source files in target directory."""
    py_files = []
    for root, dirs, files in os.walk(target_dir):
        if exclude_tests:
            dirs[:] = [d for d in dirs if d not in ('tests', 'docs', '.git', '__pycache__', 'venv', 'build', 'dist')]
        for file in files:
            if file.endswith('.py'):
                if exclude_tests and (file.startswith('test_') or file == 'setup.py'):
                    continue
                py_files.append(os.path.join(root, file))
    py_files.sort()
    return py_files


def load_python_files_from_list(file_list_path: str, repo_root: str = ".") -> List[str]:
    """Load python file paths from text file generated by Thi."""
    py_files = []
    if not os.path.exists(file_list_path):
        print(f"[ERROR] File list path not found: {file_list_path}", file=sys.stderr)
        return py_files

    with open(file_list_path, 'r', encoding='utf-8') as f:
        for line in f:
            clean_line = line.strip().replace("\\", "/")
            if clean_line and clean_line.endswith('.py'):
                full_path = os.path.abspath(os.path.join(repo_root, clean_line))
                if os.path.exists(full_path):
                    py_files.append(full_path)
    return py_files


def compute_file_hash(filepath: str) -> str:
    """Quickly compute MD5 hash of file content for change detection."""
    try:
        with open(filepath, 'rb') as f:
            return hashlib.md5(f.read()).hexdigest()
    except Exception:
        return ""


class ParseCache:
    """Local cache manager to avoid re-parsing unchanged files."""
    def __init__(self, cache_file: str):
        self.cache_file = cache_file
        self.data: Dict[str, str] = {}
        self.load()

    def load(self):
        if os.path.exists(self.cache_file):
            try:
                with open(self.cache_file, 'r', encoding='utf-8') as f:
                    self.data = json.load(f)
            except Exception:
                self.data = {}

    def save(self):
        try:
            cache_dir = os.path.dirname(self.cache_file)
            if cache_dir and not os.path.exists(cache_dir):
                os.makedirs(cache_dir, exist_ok=True)
            with open(self.cache_file, 'w', encoding='utf-8') as f:
                json.dump(self.data, f, indent=2)
        except Exception as e:
            print(f"[WARN] Could not save cache: {e}", file=sys.stderr)

    def is_unchanged(self, filepath: str, current_hash: str) -> bool:
        return self.data.get(filepath) == current_hash

    def update(self, filepath: str, current_hash: str):
        self.data[filepath] = current_hash


class KafkaSender:
    def __init__(self, broker: str):
        self.broker = broker
        try:
            from kafka import KafkaProducer
            self.producer = KafkaProducer(
                bootstrap_servers=broker,
                value_serializer=lambda v: json.dumps(v).encode('utf-8'),
                acks='all',
                retries=3
            )
            print(f"[INFO] Connected to Kafka Broker at {broker}")
        except Exception as e:
            print(f"[ERROR] Could not connect to Kafka broker {broker}: {e}", file=sys.stderr)
            sys.exit(1)

    def send(self, topic: str, message: Dict[str, Any]):
        self.producer.send(topic, value=message)

    def flush(self):
        self.producer.flush()

    def close(self):
        self.producer.close()


def main():
    parser = argparse.ArgumentParser(description="Incremental CPG Parser Service for Lab 04")
    parser.add_argument("--repo-dir", type=str, default="diffusers/src", help="Path to repository or source directory")
    parser.add_argument("--file-list", type=str, default=None, help="Path to txt file listing python files (e.g. Thi/python_files_list.txt)")
    parser.add_argument("--kafka-broker", type=str, default=None, help="Kafka broker host:port (e.g. localhost:9092)")
    parser.add_argument("--schema-dir", type=str, default="Ty/schemas", help="Directory containing JSON schemas")
    parser.add_argument("--cache-file", type=str, default="sang/.parse_cache.json", help="Path to incremental parse cache file")
    parser.add_argument("--force-reparse", action="store_true", help="Force re-parsing of all files ignoring cache")
    parser.add_argument("--dry-run", action="store_true", help="Perform parsing without sending to Kafka")
    parser.add_argument("--limit", type=int, default=0, help="Limit number of files to process (0 = all)")
    parser.add_argument("--include-tests", action="store_true", help="Include test files")

    args = parser.parse_args()

    repo_dir = os.path.abspath(args.repo_dir)

    if args.file_list:
        py_files = load_python_files_from_list(args.file_list, repo_root=".")
        total_files = len(py_files)
        print(f"[INFO] Loaded {total_files} files from list: {args.file_list}")
    else:
        if not os.path.exists(repo_dir):
            print(f"[ERROR] Target directory not found: {repo_dir}", file=sys.stderr)
            sys.exit(1)
        py_files = discover_python_files(repo_dir, exclude_tests=not args.include_tests)
        total_files = len(py_files)

    schemas = load_schemas(args.schema_dir)
    cache = ParseCache(args.cache_file)

    if args.limit > 0:
        py_files = py_files[:args.limit]

    print(f"==================================================")
    print(f" Incremental CPG Parser Service (Sang)")
    print(f" Target Source: {'File List: ' + args.file_list if args.file_list else 'Repo Dir: ' + repo_dir}")
    print(f" Discovered .py files: {total_files} (Processing: {len(py_files)})")
    print(f" Incremental Cache: {args.cache_file} (Force: {args.force_reparse})")
    print(f" Mode: {'DRY RUN (No Kafka)' if args.dry_run or not args.kafka_broker else f'KAFKA ({args.kafka_broker})'}")
    print(f"==================================================")

    sender = None
    if not args.dry_run and args.kafka_broker:
        sender = KafkaSender(args.kafka_broker)

    stats = {
        "processed_files": 0,
        "skipped_files": 0,
        "nodes_emitted": 0,
        "edges_emitted": 0,
        "errors": 0
    }

    start_time = time.time()

    for idx, filepath in enumerate(py_files, 1):
        rel_path = os.path.relpath(filepath, ".").replace("\\", "/")
        current_hash = compute_file_hash(filepath)

        # Check incremental cache
        if not args.force_reparse and cache.is_unchanged(rel_path, current_hash):
            stats["skipped_files"] += 1
            if idx % 100 == 0 or idx == len(py_files):
                print(f"[{idx}/{len(py_files)}] Skipped (Unchanged): {os.path.basename(filepath)}")
            continue

        metadata_evt, nodes, edges, error_evt = parse_python_file(filepath, repo_root=".")

        if error_evt:
            stats["errors"] += 1
            if validate_message(error_evt, schemas.get(TOPIC_ERRORS)):
                if sender:
                    sender.send(TOPIC_ERRORS, error_evt)
                elif args.dry_run:
                    print(f"[DRY-RUN][ERROR] {filepath}: {error_evt['error_message']}")
        else:
            stats["processed_files"] += 1
            stats["nodes_emitted"] += len(nodes)
            stats["edges_emitted"] += len(edges)
            cache.update(rel_path, current_hash)

            # 1. Source Metadata
            if validate_message(metadata_evt, schemas.get(TOPIC_METADATA)):
                if sender:
                    sender.send(TOPIC_METADATA, metadata_evt)

            # 2. Node Events
            for node_evt in nodes:
                if validate_message(node_evt, schemas.get(TOPIC_NODES)):
                    if sender:
                        sender.send(TOPIC_NODES, node_evt)

            # 3. Edge Events
            for edge_evt in edges:
                if validate_message(edge_evt, schemas.get(TOPIC_EDGES)):
                    if sender:
                        sender.send(TOPIC_EDGES, edge_evt)

        if idx % 20 == 0 or idx == len(py_files):
            print(f"[{idx}/{len(py_files)}] Processed: {os.path.basename(filepath)} | Skipped: {stats['skipped_files']} | Nodes: {stats['nodes_emitted']} | Edges: {stats['edges_emitted']}")

    if sender:
        sender.flush()
        sender.close()

    cache.save()

    elapsed = time.time() - start_time
    print(f"\n==================================================")
    print(f" Execution Summary")
    print(f" Files Processed (Re-parsed): {stats['processed_files']}")
    print(f" Files Skipped (Unchanged): {stats['skipped_files']}")
    print(f" Total Nodes Emitted: {stats['nodes_emitted']}")
    print(f" Total Edges Emitted: {stats['edges_emitted']}")
    print(f" Errors Encountered: {stats['errors']}")
    print(f" Time Elapsed: {elapsed:.2f} seconds")
    print(f"==================================================")


if __name__ == "__main__":
    main()
